SIM_NAME="t"
USER_SETTING={'MODEL_DISABLE': [('Dynamics', 'ug'), ('t', 'test')]}
MOD_INDEX=['AroCore', 'Dynamics']
AROCLASS_INDEX=[]
ACPCLASS_INDEX=[]
TOOL_INDEX=[]
MAP_INDEX=['PlanarMech', 'body3']
MODEL_INDEX=['test', 'PM1', 'PM2', 'PM3']
COM_INDEX=[""]
