SIM_NAME="t"
USER_SETTING={'ACP_DEPTH': 15, 'MODEL_DISABLE': [('Dynamics', 'ug'), ('Dynamics', 'base')]}
MOD_INDEX=['AroCore', 'Dynamics']
AROCLASS_INDEX=[]
ACPCLASS_INDEX=[]
TOOL_INDEX=[]
MAP_INDEX=['init']
MODEL_INDEX=['New model']
COM_INDEX=["com"]
