SIM_NAME="t"
USER_SETTING={'MODEL_DISABLE': [('t', 'm1'), ('t', 'm2'), ('t', 'test'), ('t', 'PM')]}
MOD_INDEX=['AroCore', 'Dynamics']
AROCLASS_INDEX=[]
ACPCLASS_INDEX=[]
TOOL_INDEX=[]
MAP_INDEX=['body3', 'PlanarMech']
MODEL_INDEX=['test', 'PM']
COM_INDEX=[""]
