SIM_NAME="Complict"
USER_SETTING={'MODEL_DISABLE': [('Dynamics', 'PM3'), ('Dynamics', 'PM2'), ('Dynamics', 'PM1'), ('Dynamics', 'ug')]}
MOD_INDEX=['AroCore', 'Dynamics']
AROCLASS_INDEX=[]
ACPCLASS_INDEX=[]
TOOL_INDEX=[]
MAP_INDEX=['init']
MODEL_INDEX=['col-1']
COM_INDEX=[""]
